### ISSUE TITLE
Add support for defining common_dimensions and tag_dimensions similar to the AWS mod

### ISSUE THREAD

**Issue by chrislwade** [turbot/steampipe-mod-azure-tags#34]
**Is your feature request related to a problem? Please describe.**
In larger organizations, subscription_id and resource_group aren't always enough to allow teams to rapidly identify and act on findings.

**Describe the solution you'd like**
Implement common_dimensions and tag_dimensions support similar to the existing AWS mod implementation.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by misraved** [comment]
Thanks @chrislwade for pointing out the missing feature 👍 !!

**Comment by ParthaI** [comment]
This issue is being closed as it has been resolved in the following PR: https://github.com/turbot/steampipe-mod-azure-tags/pull/35.
